package com.ecommerce.enums;

public enum NotificationType {
    ORDER_PLACED,
    ORDER_CONFIRMED,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    REVIEW_APPROVED,
    COUPON_ADDED,
    PRICE_DROP,
    BACK_IN_STOCK,
    GENERAL
}
